M48
; DRILL file {KiCad 9.0.9-9.0.9~ubuntu24.04.1} date 2026-09-22T10:11:11+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-22T10:11:11+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.9-9.0.9~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C7.000
%
G90
G05
T1
X128.75Y-90.91
X145.25Y-90.91
M30
